<?php

	/** @var \Mageplaza\Productslider\Block\AbstractSlider $block */

	if ($items = $block->getProductCollection()):
		$mode = 'grid';
		$uom = "EA";
		$stockConfig = $this->helper('DCKAP\Extension\Helper\Data')->getViewInventoryByLocation();
		$dckapCatalogHelper = $this->helper('DCKAP\Catalog\Helper\Data');
		$cartHelper = $this->helper('Magento\Checkout\Helper\Cart');
		$title = $block->getTitle();
		$extensionHelper = $this->helper('DCKAP\Extension\Helper\Data');
		$guestPriceDisplay = $extensionHelper->getGuestPriceDisplay();
		$checklogin = $dckapCatalogHelper->checkloggedin();
		$validateuserData = $extensionHelper->getEcommUserData();
		$allowonaccount ="no";
		if(isset($validateuserData) && !empty($validateuserData)){
			$allowonaccount = $validateuserData['allowOnAccount'];
		}
		?>
        <div class="mp-product-slider-block block widget block-products-list <?php echo $mode; ?>">
            <h2 class="mp-product-slider-title"><?php echo $block->getTitle(); ?></h2>
            <p class="mp-ps-info"><?php echo $block->getDescription(); ?></p>
        </div>
        <div class="block-content">
            <div class="products-<?php echo $mode; ?> <?php echo $mode; ?>">
                <ol class="product-items widget-viewed-grid">
					<?php $iterator = 1; ?>
                    <div id="mp-list-items-<?php echo $block->getSliderId(); ?>" class="owl-carousel owl-theme">
						<?php foreach ($items as $_item):
							$offline = 0;
							if ($offline = $_item->getCustomAttribute('offline')) {
								$offline = $_item->getData('offline');
							}
							echo ($iterator++ == 1) ? '<li class="product-item product-slider"">' : '</li><li class="product-item product-slider"">'; ?>
                            <div class="slider-product-item-info product-item-info" id="product-id-<?php echo $_item->getId(); ?>" <?php if (!($_item->getTypeId() == 'configurable' || $_item->getTypeId() == 'grouped')) { ?>data-product-id="<?php echo $_item->getId(); ?>" <?php } ?>>
                                <a href="<?php echo $block->getProductUrl($_item); ?>" class="product photo slider-product-item-photo">
									<?php echo $block->getImage($_item, 'recently_viewed_products_grid_content_widget')->toHtml(); ?>
                                </a>
                                <div class="product details slider-product-item-details">
                                    <strong class="product name product-item-name">
                                        <a title="<?php echo $block->escapeHtml($_item->getName()); ?>" href="<?php echo $block->getProductUrl($_item); ?>">
											<?php echo $block->escapeHtml($_item->getName()); ?>
                                        </a>
                                    </strong>
									<?php if ($_item->isSaleable()):
										if ($_item->getTypeId() != 'configurable' && $_item->getTypeId() != 'grouped') {
											if((!$checklogin && $guestPriceDisplay)) {
												echo $block->getProductPrice($_item);
											}
											else{
												echo $block->getProductPrice($_item);
											}
										}
									endif;
										if ($block->canShowReview()):
											echo $block->getReviewsSummaryHtml($_item, 'short', true);
										endif; ?>
                                    <div class="product actions slider-product-item-actions">
										<?php if ($block->canShowAddToCart()): ?>
                                            <div class="actions-primary">
												<?php if (!$offline || $offline == "0") {
													if ($_item->getTypeId() != 'configurable' && $_item->getTypeId() != 'grouped') {
														if ($dckapCatalogHelper->getStockDisplay() > 0) { ?>
                                                            <div class="stock unavailable" title="<?= __('Availability') ?>">
                                                                <span><?= __('Out of stock') ?></span>
                                                            </div>
															<?php if ($dckapCatalogHelper->getStockDisplay() > 1) { ?>
                                                                <div class="availability only" style="width: 100%;">
																	<?/*= __('Only ') */?><!--<strong>0</strong>--><?/*= __(' left') */?>
                                                                </div>
															<?php }
														}
													}
												}
													if ($_item->isSaleable()):
														if ($_item->getTypeId() == 'configurable' || $_item->getTypeId() == 'grouped') { ?>
                                                            <a href="<?php echo $block->getProductUrl($_item); ?>"
                                                               class="button action"><?= __('Choose an Option') ?></a>
														<?php } else {
															if (!$offline || $offline == "0") { ?>
                                                                <form id="myForm<?php echo $_item->getId(); ?>" >
																	<?php echo $block->getBlockHtml('formkey'); ?>
                                                                    <input type="number" name="qty" class="qty" maxlength="12" value="1" title="<?php echo __('Qty') ?>" min="1" required class="input-text qty form-control" product_id="<?= $block->escapeHtmlAttr($_item->getId()) ?>" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())); ?>"/>
                                                                    <input type="hidden" name="custom_uom" value="<?php echo $uom; ?>"/>
                                                                    <input type="hidden" name="req_qty" class="req_qty_<?php echo $_item->getId(); ?>" value="1"/>
                                                                    <input type="hidden" name="erp_qty" class="erp_qty" value="1"/>
                                                                    <input type="hidden" name="product_id" class="product_id" value="<?= $_item->getId(); ?>"/>
                                                                    <input type="hidden" name="product_sku" class="product_sku" value="<?= $_item->getSku(); ?>"/>
                                                                    <input type="hidden" name="allowonaccount" class="allowonaccount" value="<?php echo $allowonaccount; ?>"/>
                                                                    <button class="submit action tocart primary mageplaza-product-slider-button" type="button" title="<?php echo __('Add to Cart') ?>" form_id="myForm<?php echo $_item->getId(); ?>" action="<?php echo $cartHelper->getAddUrl($_item); ?>" method="post">
                                                                        <span><?php echo __('Add to Cart') ?></span>
                                                                    </button>
                                                                </form>
															<?php }
														}
													endif; ?>
                                            </div>
										<?php endif; ?>
                                    </div>
                                </div>
                            </div>
							<?php echo ($iterator == count($items) + 1) ? '</li>' : '';
						endforeach; ?>
                    </div>
                </ol>
            </div>
			<?php echo $block->getPagerHtml(); ?>
        </div>
        <script>
            require(['jquery','Magento_Customer/js/customer-data', 'mageplaza/core/owl.carousel' ], function ($,customerData) {
                $(".mageplaza-product-slider-button").off().on("click", function(e) {
                    e.preventDefault();
                    var form_id = $(this).attr("form_id");
                    form_id ="#"+form_id;
                    var url_form = $(this).attr('action');
                    $.ajax({
                        type: 'POST',
                        url: url_form,
                        data: $(form_id).serialize(),
                        error: function()
                        {
                            console.log("Request Failed");
                        },
                        success: function(response)
                        {
                            console.log("Request done");
                            var sections = ['cart'];
                            customerData.invalidate(sections);
                            customerData.reload(sections, true);
                            location.reload();
                            $(window).scrollTop(0);
                        }
                    });
                    return false;
                });
                $(document).ready(function () {
                    $(document).on('keydown keypress keyup','.qty', function () {
                        var qty = $(this).val();
                        var id = $(this).attr("product_id");
                        $(".req_qty_"+id).val(qty);
                    });

                });

                $('#mp-list-items-<?php echo $block->getSliderId(); ?>').owlCarousel(<?php echo($block->getAllOptions())?>);
            });
        </script>
	<?php endif; ?>

